<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.28">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2010-05-01">
<meta name="description" content="Updating analysis presented by Richard Breen in the 1996 Report on Social Attitudes in Northern Ireland.">

<title>The Determinants of National Identity in Northern Ireland: Is Religion All That Matters? – Diggy Digs Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./assets/img/favicons/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-013882879a21c3ca3416aac467d3c23f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-013882879a21c3ca3416aac467d3c23f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-013882879a21c3ca3416aac467d3c23f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1e0d785306329dd87d93ab7c32bdc37a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-f6530c4cab28cdaa8f4f88d19fa58afb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-1e0d785306329dd87d93ab7c32bdc37a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta property="og:title" content="The Determinants of National Identity in Northern Ireland: Is Religion All That Matters? – Diggy Digs Data">
<meta property="og:description" content="Updating analysis presented by Richard Breen in the 1996 Report on Social Attitudes in Northern Ireland.">
<meta property="og:site_name" content="Diggy Digs Data">
</head>

<body class="nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    window.setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      window.setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    window.hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(darkModeDefault) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const darkModeDefault = false;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !window.hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
    };
    // Switch to dark mode if need be
    if (window.hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./assets\img\brand.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Diggy Digs Data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">Analytics</span>
    </span>
  </li>  
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">Tutorials</span>
    </span>
  </li>  
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">Reviews</span>
    </span>
  </li>  
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">Upcomings</span>
    </span>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/diggydigsdata"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Determinants of National Identity in Northern Ireland: Is Religion All That Matters?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Northern Ireland</div>
    <div class="quarto-category">Sociology</div>
  </div>
  </div>

<div>
  <div class="description">
    Updating analysis presented by Richard Breen in the 1996 Report on Social Attitudes in Northern Ireland.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 1, 2010</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>My project will serve to update the analysis presented by Richard Breen in the 1996 Report on Social Attitudes in Northern Ireland. This chapter, entitled ‘Who Wants a United Ireland? Constitutional preferences among Catholics and Protestants’, uses the Northern Ireland Social Attitudes surveys to explore patterns in self-identification among Catholics and Protestants, and the ways they correlate with constitutional identification.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> His results derive from a 5-year survey period; 1989-1994. He examines the effects of gender, age, class and education but indicates that national and constitutional identity in Northern Ireland is defined overwhelmingly by religion and that the resultant constitutional identity has essentially segregated Northern Irish politics not along social lines, but along religious ones. ‘Clearly the most important characteristic that distinguishes those who favour the retention of the Union with Britain from those who favour a united Ireland is religion.’<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Nonetheless, he is reluctant to make forecasts for the future and suggests that the unpredictable nature of the region would make it almost impossible. My report will focus on the subsequent decade of surveys conducted on identity in Northern Ireland and will attempt to assess whether religion is as important in determining national identity while investigating other explanations.</p>
<p>As it happens, subsequent years witnessed a series of landmark moments in Northern Irish history. Indeed, in a discussion of preferred long-term policies for Northern Ireland Breen alludes to the potential future implications of the 1994 ceasefires. The studies sandwich the 1998 Good Friday Agreement, the most celebrated moment in the move towards cessation of armed hostilities, standing out within a period of emerging stability. This momentum has persisted and, after several false–starts, the Northern Irish Assembly appears to have made a breakthrough in the bid to establish a sustainable devolved government. The development of this government was conditional on a compromise between the paragons of Northern Ireland’s parallel identities; with the DUP and Sinn Fein forming a unique power-sharing coalition in order to assure Northern Ireland’s autonomy.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> My study ought therefore prove an interesting counterpoint to Breen’s, with the change of the era forcing a reconsideration of the degree to which constitutional preferences in Northern Ireland can be stated to be unconditionally established along lines of religiosity. It will be structured around re-visiting Breen’s conclusion that ‘the major factor that explains variation in constitutional preferences is community background or religion, distinguishing Catholics from Protestants.’ In updating the Breen study my null hypotheses can be stated as:</p>
<p>‘Religion is still the dominant influence on identity.’</p>
<p>‘The strength of religion as a predictor of identity is undiminished.’</p>
</section>
<section id="justification-and-contextualisation" class="level2">
<h2 class="anchored" data-anchor-id="justification-and-contextualisation">Justification and Contextualisation</h2>
<p>Four readings have guided my thinking on the subject and compose a chronological context for the study. Foremost among them is, of course, the chapter by Richard Breen in the 1996 Report on Social Attitudes in Northern Ireland. There is obvious justification for the repetition of survey methods for the purposes of longitudinal comparative studies. Of particular relevance, therefore, to my own study was the development of a chronological framework; the following literature supported my proposal.</p>
<ul>
<li>Governing Without Consensus (1971) by Richard Rose<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></li>
</ul>
<p>The book consists of three parts. Firstly, the context and theoretical framework, in which he traces the development of a discordant political system and its inability to forget the past and efforts to make sense of it. Secondly, Rose designed his own ‘Loyalty Survey’, which achieved a remarkably high response rate (86.2 per cent) and used trained interviewers to gather data from around 1300 households. The results demonstrate how the majority of people were considering Ulster’s situation as separate from Britain; it was its own complex entity in a way. The results are surprising given the escalation of tensions that quickly followed. The final part deals with potential constitutional outcomes. He offers 12.</p>
<ul>
<li>Interpreting Northern Ireland (1990) by John Whyte<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></li>
</ul>
<p>Whyte accumulated a vast array of survey findings charting changes in self-identification at fairly regular intervals. In this way, his objectives are very much in keeping with my own. It is further enlightening in the sense of showing the different methods employed by sociologists to determine measures of religiosity and of cultural, social and political identification. Based on my reading, it would appear that this practice of re-treading questions is not unprecedented. In fact, the situation seemed to justify it, particularly in light of the unpredictable social context. Indeed, Moxon-Browne explains that he used the same key questions in his 1983 book ‘Nation, Class and Creed in Northern Ireland’ based on a 1978 survey as Rose had done 10 years earlier. There is a parallel to be drawn to my own proposed study. Rose used a survey that was carried out just months before the Troubles really began, and Moxon-Browne was in a position to assess what 10 years of escalating tensions had done to identity.</p>
<ul>
<li>‘National Identity’ (1991) by Edward Moxon-Browne<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></li>
</ul>
<p>Moxon-Browne adopts a similar tone to Breen. ‘Although the lines of division are often considered to be religious in character, religion is best seen as a badge of difference - the visible symbol of deeper and less tangible attachments to national ’roots’. Today, these conflicting interpretations manifest themselves in two sets of apparently irreconcilable political aspirations.’ However, he elaborates more on why that may be the case and proposes that endogamy and insularity have been core to the prolonged segregation and political polarization. One interesting point he makes: ‘In 1968, just before the onset of civil unrest in Northern Ireland, 20% of Protestants claimed to feel ’Irish’. Ten years later, after having borne the brunt of the IRA campaign, Protestants have swung more definitely towards adopting the label ‘British’. This causes me to wonder what effect the Good Friday Agreement of 1998 and the sustained period of peace will have had on identity.</p>
<p>Similarly, whereas Breen identifies no conclusive evidence for the influence of class Moxon-Browne is adamant that towards the end of the 1970s class was a factor in identity, or at least the intensity with which identity was expressed. He points to a fading away of this influence, one which may be slow-burn. Given the closing of the gap in recent years changes may be evident in the surveys I’ll be dealing with.</p>
<p>Since Breen’s study concluded in 1994, the political landscape in Northern Ireland has undergone drastic re-formulation. More than ever, it seems, a balanced assessment of Northern Ireland’s constitutional driving forces is possible. From the late 1980s talks had been ongoing over ways to resolve the sectarian conflict in Northern Ireland but it was not until April 1994 that the Provisional IRA instituted a three-day ceasefire. By 31 August a permanent ceasefire was promised. After a period of dialogue and a stop-start period of hostilities followed by ceasefires, Northern Ireland’s major political parties finally appeared to unite in their commitment to peace with the signing of the Good Friday Agreement in 1998, followed shortly by the election of a Northern Irish Assembly in 1999. The formation of a devolved Northern Irish executive represented an end to Direct Rule from London for the first time since March 1972. Devolution took time to settle, but Northern Ireland now has a functioning Assembly with a cross-community Executive. Departments are allocated in proportion to number of seats held. Most recently, there has been an unprecedented cross-community collaboration between DUP and Sinn Fein.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> This belies, therefore, the shift towards the more extreme wings of the political spectrum.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>The issues I hope this updated study will illuminate are, therefore, whether these changes have re-shaped ethnic national identities in Northern Ireland. This will be gauged principally by constitutional preferences, most significantly the support for either a United Ireland or for some form of Union with Britain. Consequently, I will adopt a more focussed approach than Breen, centring my examination on the Catholic constitutional preferences, by way of investigating the desire for a United Ireland, and its potential re-evaluation in light of a devolved government. It is tempting to say that the strength of ethnic/national identity can be eroded as issues around which conflict centres diminish in strength. Economic growth, and the decrease in violence may have softened relations. What makes the topic potentially so fascinating, then, is that the parties elected to forge these alliances are the most extreme wings of Northern Ireland’s unique political spectrum. In other words, I want to see why the period of greatest compromise has coincided with the rise of the most unrelenting of the political parties; namely Sinn Fein and the DUP. They have established their mainstream credentials by being entrusted with the task of working together.</p>
<p>Through a through statistical deconstruction of Catholic identity I hope to be able to arrive at a more rounded appreciation of the extent to which religion determines the constitutional preferences because it seems as though, in accepting compromise and prioritizing autonomy, even in the most rudimentary sense of the word through devolution, there must be recognition of something beyond religion as the driving force in an evolving complexity of constitutional realities.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<p>The practicalities of my project were modelled on the Breen study. Obviously, certain constraints ensured I adopted a more focussed approach.&nbsp; Breen used the NI Social Attitudes Survey, from 1989-1994, with the exception of 1992 when there was no survey<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a><a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> From 1998, this has been replaced by the NI Life and Times Survey.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> The central justification for my update is my desire to assess the impact of the Good Friday Agreement of 1998. A subsequent landmark moment in terms of the Northern Irish constitutional arrangement arrived in the aforementioned power-sharing agreement of 2007. To arrive at logical conclusions, it appeared necessary to merge time periods in order to serve as broader points of comparison. So, 1989-1994 equals Breen’s years, 2000-2004 is the post-GFA period, noteworthy also because all the variables in the surveys from these years remain consistent with those established during the course of Breen’s study. Finally, 2007-2008; not only does this correspond with power-sharing and is a reflection on the present-day situation, it also sees a tweaking in the constitutional preference question, rendering it somewhat more positive with regard to the union with Great Britain, in a way which may be encouraging to Catholics.</p>
<p>Data was gathered from two sources; the NI Social Attitudes Survey (1989-1998), the subsequent NI Life and Times Survey (1998-2008). A pooled dataset comprising 1989-2004 was sourced via the UK Data Archive.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> The remaining datasets were downloaded from the NILTS website. The datasets were then stacked one on top of each other using the SPSS merge procedure. The pooled file did not have all the same variables as did NILTS, most notably the variable for main religious affiliation i.e.&nbsp;Catholic, Protestant, no religion – RELIGCAT, however a recode of religious denominations was able to produce this variable. Furthermore, it had three supplementary datasets relating to Northern Irish elections which it was necessary to exclude. Table 1 illustrates the sample sizes for each year. Between 1989-1994 the total count is 5029; for 2000-2004 it is 9000 and for 2007-2008 it is 2394. Post-2004 the size of the survey has decreased from 1800 to 1216 in 2008 due to lack of funding. In 2008, the most recent survey, the NI Life and Times Survey reported a response rate of 60%, perhaps low enough to leave it vulnerable to non-response bias.</p>
<section id="table-1-sample-size-per-year" class="level3">
<h3 class="anchored" data-anchor-id="table-1-sample-size-per-year">Table 1: Sample Size Per Year</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 22%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Frequency</th>
<th>Percent</th>
<th>Valid Percent</th>
<th>Cumulative Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NISA 1989</td>
<td>86</td>
<td>3.4%</td>
<td>3.4%</td>
<td>3.4%</td>
</tr>
<tr class="even">
<td>NISA 1990</td>
<td>89</td>
<td>3.6%</td>
<td>3.6%</td>
<td>7.0%</td>
</tr>
<tr class="odd">
<td>NISA 1991</td>
<td>90</td>
<td>3.6%</td>
<td>3.6%</td>
<td>10.6%</td>
</tr>
<tr class="even">
<td>NISA 1993</td>
<td>84</td>
<td>3.3%</td>
<td>3.3%</td>
<td>14.0%</td>
</tr>
<tr class="odd">
<td>NISA 1994</td>
<td>151</td>
<td>6.0%</td>
<td>6.0%</td>
<td>20.0%</td>
</tr>
<tr class="even">
<td>NISA 1995</td>
<td>151</td>
<td>6.0%</td>
<td>6.0%</td>
<td>26.0%</td>
</tr>
<tr class="odd">
<td>NISA 1996</td>
<td>78</td>
<td>3.1%</td>
<td>3.1%</td>
<td>29.1%</td>
</tr>
<tr class="even">
<td>NILT 1998</td>
<td>1800</td>
<td>7.2%</td>
<td>7.2%</td>
<td>36.3%</td>
</tr>
<tr class="odd">
<td>NILT 1999</td>
<td>2200</td>
<td>8.7%</td>
<td>8.7%</td>
<td>45.0%</td>
</tr>
<tr class="even">
<td>NILT 2000</td>
<td>1800</td>
<td>7.2%</td>
<td>7.2%</td>
<td>52.2%</td>
</tr>
<tr class="odd">
<td>NILT 2001</td>
<td>1800</td>
<td>7.2%</td>
<td>7.2%</td>
<td>59.3%</td>
</tr>
<tr class="even">
<td>NILT 2002</td>
<td>1800</td>
<td>7.2%</td>
<td>7.2%</td>
<td>66.5%</td>
</tr>
<tr class="odd">
<td>NILT 2003</td>
<td>1800</td>
<td>7.2%</td>
<td>7.2%</td>
<td>73.7%</td>
</tr>
<tr class="even">
<td>NILT 2004</td>
<td>1800</td>
<td>7.2%</td>
<td>7.2%</td>
<td>80.8%</td>
</tr>
<tr class="odd">
<td>2005</td>
<td>1200</td>
<td>4.8%</td>
<td>4.8%</td>
<td>85.6%</td>
</tr>
<tr class="even">
<td>2006</td>
<td>1230</td>
<td>4.9%</td>
<td>4.9%</td>
<td>90.5%</td>
</tr>
<tr class="odd">
<td>2007</td>
<td>1179</td>
<td>4.7%</td>
<td>4.7%</td>
<td>95.2%</td>
</tr>
<tr class="even">
<td>2008</td>
<td>1215</td>
<td>4.8%</td>
<td>4.8%</td>
<td>100.0%</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>25149</strong></td>
<td><strong>100%</strong></td>
<td><strong>100%</strong></td>
<td><strong>100%</strong></td>
</tr>
</tbody>
</table>
<p>Surveys were carried out through face-to-face interviews and self-completion, using random sampling to select persons aged 18+ living in private residences. For the purposes of ensuring a representative sample, the surveys only use one adult from each selected house. So, in houses with multiple adults one person is randomly chosen for the survey. Consequently, it is necessary to use weighting to account for the lower probability of selection in larger households.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a><a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
<p>The study demands an investigation of the religious background of all the respondents. This is derived from the RELIGCAT summary variable based on the question on ‘religious denomination’. This will serve as the independent variable underlining my ability to make assessments on the influence of religion on the following dependent indicators of identity:</p>
<p>Constitutional preferences. This variable is measured by the question ‘Do you think the long-term policy for Northern Ireland should be for it to remain part of the United Kingdom or to reunify with the rest of Ireland?’. For the 2007 survey, the question was changed. Respondents were asked if they wished to remain part of the UK either with direct rule i.e.&nbsp;governed from London, or with devolved Government i.e.&nbsp;the NI Assembly and Executive. This devolved option is a sort of halfway house, offering Catholics a slightly more attractive proposition perhaps and complicating comparisons.</p>
<p>National identity. This variable is established through the question ‘which of these best describes the way you usually think of yourself? ‘British’, ‘Irish’, ‘Ulster’, ‘Northern Irish’ ‘other’.</p>
<p>Constitutional identity. This variable is introduced through the question ‘Generally speaking, do you think of yourself as a Unionist, a Nationalist or neither?’ The responses are therefore quite straightforward and easy to operationalise.</p>
<p>Political party preference-this variable (NIPTYID4) is derived from the answers to two questions:</p>
<p>“If there was a general election tomorrow, which party would you vote for?” (NIPTYID1This is for 1989-2004).</p>
<p>Then, for those who answer non-NI parties (Labour, Conservative, Liberal Democrats), asks:</p>
<p>NIPTYID3: “If there were a general election in which only Northern Ireland parties were standing, which one do you think you would be most likely to support?”</p>
<p>In 2007 and 2008, the survey switched to asking “Which party do you feel closest to, even if you do not always vote for them?” (POLPARTY). With the latter question, it may be easier for people to say ‘none’. Strictly speaking, therefore, they are not comparable.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></p>
<p>The defining feature of my study is that Northern Ireland has undergone change, and that perhaps the findings of Breen will not necessarily hold hard and fast in the present economic and political climate. For this reason, it is necessary to investigate another factor in determining identity in Northern Ireland. That is, social class. For a long time, it would have been held that social class in Northern Ireland was also determined exclusively by religion and that opportunities were limited for Catholics. However, this can no longer be stated unequivocally. For this reason, it is possible that all along social class has been the primary indicator of constitutional preferences, it was merely obscured by its inherent historical ties with religious identity. I am interested to see whether different elements of society support different constitutional options. Perhaps this will prove at least as important as religion in determining the way Northern Irish envisage their future.</p>
<p>Social class-as a social class indicator Breen used RGHCLASS, the Goldthorpe-Heath schema.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> In 2007 and 2008 the NS-SEC Analytical classification is used.<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a> Unfortunately, the latter is too much of a revision on the former to derive a common variable. In spite of this, Breen’s categories can be viewed as similar in terms of a social class rank order. In this, Breen’s ‘salariat would correspond to ‘professional and managerial’, for example.</p>
</section>
</section>
<section id="data-analyses" class="level2">
<h2 class="anchored" data-anchor-id="data-analyses">Data Analyses</h2>
<p>My priorities in terms of updating Breen were identifying the influence of religion on identity and constitutional preferences. Table 2 effectively merges Tables 1 and 2 from the Breen report, which are titled ‘Preferred long-term policy for Northern Ireland (%) and ‘Preferred long-term policy for Northern Ireland by religion (%)’ respectively.</p>
<section id="table-2-preferred-long-term-policy-for-ni-by-religion" class="level3">
<h3 class="anchored" data-anchor-id="table-2-preferred-long-term-policy-for-ni-by-religion">Table 2: Preferred Long-Term Policy for NI by Religion</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th>Religion</th>
<th>Year</th>
<th>Remain Part of UK (%)</th>
<th>Direct Rule (%)</th>
<th>Devolution (%)</th>
<th>Reunify Ireland (%)</th>
<th>Other Option (%)</th>
<th>Don’t Know (%)</th>
<th>Not Answered (%)</th>
<th>Total (%)</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Catholics</td>
<td>1989-1994</td>
<td>32.1</td>
<td>-</td>
<td>-</td>
<td>54.6</td>
<td>4.5</td>
<td>7.7</td>
<td>1.2</td>
<td>100.0</td>
<td>1499</td>
</tr>
<tr class="even">
<td></td>
<td>2000-2004</td>
<td>20.1</td>
<td>-</td>
<td>-</td>
<td>49.0</td>
<td>13.5</td>
<td>17.4</td>
<td>0.0</td>
<td>100.0</td>
<td>3384</td>
</tr>
<tr class="odd">
<td></td>
<td>2007-2008</td>
<td>40.9</td>
<td>5.3</td>
<td>35.6</td>
<td>42.9</td>
<td>9.2</td>
<td>7.1</td>
<td>0.0</td>
<td>100.0</td>
<td>4917</td>
</tr>
<tr class="even">
<td>Protestants</td>
<td>1989-1994</td>
<td>91.1</td>
<td>-</td>
<td>-</td>
<td>4.6</td>
<td>2.5</td>
<td>1.4</td>
<td>0.4</td>
<td>100.0</td>
<td>2281</td>
</tr>
<tr class="odd">
<td></td>
<td>2000-2004</td>
<td>82.6</td>
<td>-</td>
<td>-</td>
<td>4.2</td>
<td>6.8</td>
<td>6.4</td>
<td>0.0</td>
<td>100.0</td>
<td>4575</td>
</tr>
<tr class="even">
<td></td>
<td>2007-2008</td>
<td>89.0</td>
<td>20.8</td>
<td>68.2</td>
<td>3.7</td>
<td>4.8</td>
<td>2.5</td>
<td>0.0</td>
<td>100.0</td>
<td>1155</td>
</tr>
<tr class="odd">
<td>No Religion</td>
<td>1989-1994</td>
<td>73.4</td>
<td>-</td>
<td>-</td>
<td>16.1</td>
<td>5.7</td>
<td>4.3</td>
<td>0.5</td>
<td>100.0</td>
<td>440</td>
</tr>
<tr class="even">
<td></td>
<td>2000-2004</td>
<td>49.9</td>
<td>-</td>
<td>-</td>
<td>17.9</td>
<td>15.9</td>
<td>16.3</td>
<td>0.0</td>
<td>100.0</td>
<td>886</td>
</tr>
<tr class="odd">
<td></td>
<td>2007-2008</td>
<td>70.8</td>
<td>14.2</td>
<td>56.6</td>
<td>15.0</td>
<td>8.2</td>
<td>6.0</td>
<td>0.0</td>
<td>100.0</td>
<td>267</td>
</tr>
</tbody>
</table>
<p>As can be seen I expressed the constitutional preferences of Catholics, Protestants and those of no faith over the course of the three time periods discussed earlier. Hardly surprising, support for a United Ireland is derived from Catholic quarters, while support for Union with Britain is supported overwhelmingly by Protestants. However, further investigation suggests there may be factors at play beyond simply religion. For example, in the case of Catholics note the increase in don’t knows from 6-7% from 1989-1996 up to around 17-20% from 1999 to 20046 . Similarly, Protestants experience a surge in uncertainty, from 1.4% at the outset to 6.4% by 2004. In both cases, the uncertainty seems to resolve itself somewhat, returning to normal levels by the time of the 2007-2008 NILT surveys. This is not reflected in the ‘not answering’ column, which perhaps suggests that’s while people are engaged with the issue, they are unsure how best to articulate their feelings within the confines of the survey options. There is, moreover, a sharp increase in the same time periods for those saying Other - up from 2-4% to double digits. The most obvious explanation would be that the shifts are caused by the modifications in the question formatting in NILTS compared to NISA. In these most recent surveys, the option of devolution was presented. In that sense, the anomaly may be simply an artefact of the administration of the survey. However, contextually speaking, there seems sufficient cause as to whether political developments were influential. 2000-2004 represents the immediate run-up to devolution. By 2007-2008 the power-sharing accord was beginning to look increasingly likely and people would have had to come to terms with its impendency.</p>
<p>It is pertinent, therefore, to question whether this apparent willingness to embrace devolution is indicative of a softening in national self-identification among Catholics. Table 3 is a revised version of Breen’s Table 3, which was entitled ‘Responses to national identity question by religion and year (%).’</p>
</section>
<section id="table-3-catholics-responses-to-national-identity-question-by-religion-and-period" class="level3">
<h3 class="anchored" data-anchor-id="table-3-catholics-responses-to-national-identity-question-by-religion-and-period">Table 3: Catholics: Responses to National Identity Question by Religion and Period (%)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>British/Ulster (%)</th>
<th>Northern Irish (%)</th>
<th>Irish (%)</th>
<th>Total (%)</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2000-2004</td>
<td>10.3</td>
<td>26.4</td>
<td>63.2</td>
<td>100.0</td>
<td>3292</td>
</tr>
<tr class="even">
<td>2007-2008</td>
<td>9.7</td>
<td>29.0</td>
<td>61.3</td>
<td>100.0</td>
<td>920</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>10.2</strong></td>
<td><strong>27.0</strong></td>
<td><strong>62.8</strong></td>
<td><strong>100.0</strong></td>
<td>4212</td>
</tr>
</tbody>
</table>
<p>Contrary to Breen, I used a filter so that the table features only the Catholic responses. In Breen’s study, Catholic self-identification is remarkably consistent, with an average of 61.25% over the 4 years citing themselves as Irish. There is a variation of only 2 per cent over the course of his study. Similarly, they identify themselves as Northern Irish/Sometimes British, Sometimes Irish with a range of between 26 and 29 per cent, and between 10 and 13 per cent identifying as British/Ulster. In spite of the peculiarities of the previous table this consistency in self-identification continues without anomaly in my own updated studies. Indeed, there is a very slightly strengthening in attitudes, with 62.8 identifying as Irish on average between 2000 and 2008. As is highlighted by chi-square in the answer to this question Catholics are demonstrating no significant change in identity.</p>
<p>Perhaps of even more significance with regard to the increase in support for devolution is the constitutional identity of Catholics. Are people espousing nationalism at the same time as witnessing the embrace of the possibility of evolution? Table 4 addresses this issue, classifying Catholics based on their support for Unionism, Nationalism or neither.</p>
</section>
<section id="table-4-catholics-responses-to-constitutional-identity-question-by-period" class="level3">
<h3 class="anchored" data-anchor-id="table-4-catholics-responses-to-constitutional-identity-question-by-period">Table 4: Catholics: Responses to Constitutional Identity Question by Period (%)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 18%">
<col style="width: 24%">
<col style="width: 14%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Unionist (%)</th>
<th>Neither (%)</th>
<th>Nationalist (%)</th>
<th>Total (%)</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2000-2004</td>
<td>0.8</td>
<td>36.5</td>
<td>62.7</td>
<td>100.0</td>
<td>3339</td>
</tr>
<tr class="even">
<td>2007-2008</td>
<td>0.4</td>
<td>46.9</td>
<td>52.6</td>
<td>100.0</td>
<td>1242</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>0.7</strong></td>
<td><strong>38.7</strong></td>
<td><strong>60.6</strong></td>
<td><strong>100.0</strong></td>
<td>4581</td>
</tr>
</tbody>
</table>
<p>Chi-Square Tests</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Test</th>
<th>Value</th>
<th>df</th>
<th>Asymp. Sig. (2-sided)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pearson Chi-Square</td>
<td>33.580</td>
<td>2</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>Likelihood Ratio</td>
<td>33.228</td>
<td>2</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Linear-by-Linear Association</td>
<td>26.496</td>
<td>1</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>N of Valid Cases</td>
<td>4581</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>This time, we see results consistent with those of Table 2. There is a drop-off in Nationalist self-identification, falling from 62.7 per cent to 52.6. This is sizeable. However, it also highlights a surge in support for Nationalism between the Breen study and 2000. In 1989, Nationalist self-identification is at only 40 per cent, by 1994 it was 54, and between 2000 and 2004 it was at 62.7. Therefore, in spite of the rapid advance towards peace during late 80s and 90s, we see a polarizing in constitutional identity; one which, it is worth noting, is not consistent with the desire for a United Ireland, which between 1994 and 2004 fell by 5.6 per cent.&nbsp; With the losses in Nationalist support supplementing the ‘neither’ category rather than the Unionist one it also appears to lag behind the flurry of ‘don’t knows’ of 2000-2004. Thus far it would seem there are a more complex set of motivations driving the Catholic sense of identity than was first anticipated.</p>
<p>With this in mind, Table 5, which shows support for particular parties, is potentially very enlightening. Most striking in the first instance is the near-total dominance in support for nationalist parties, with 94.1 per cent in 2000-2004 and 93.5 per cent in 2007-2008. This runs entirely contrary to Table 4; there is a 30-plus percentage point differential between self-identifying as nationalist and voting as nationalist. The expected increase in middle-ground politics based on Table 4 does not hold here, with the Alliance party receiving 4.3 and 5.1 per cent of support, in spite of 36.5 and 46.9 indicating they are neither Unionist nor Nationalist. In this sense, whatever people might feel, when it comes to voting they opt for the traditional choice. On the back of table 4, the almost-exclusive support for nationalist parties is bemusing. While on the surface supporting the null hypotheses that religion determines identity, in the context of the accumulation of findings we see the picture is extremely complex.</p>
</section>
<section id="table-5-catholics-support-for-unionist-and-nationalist-parties-and-alliance-by-period" class="level3">
<h3 class="anchored" data-anchor-id="table-5-catholics-support-for-unionist-and-nationalist-parties-and-alliance-by-period">Table 5: Catholics: Support for Unionist and Nationalist Parties and Alliance by Period (%)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>DUP (%)</th>
<th>UUP (%)</th>
<th>Alliance (%)</th>
<th>SDLP (%)</th>
<th>Sinn Fein (%)</th>
<th>Total (%)</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2000-2004</td>
<td>0.5</td>
<td>1.1</td>
<td>4.3</td>
<td>65.0</td>
<td>29.1</td>
<td>100.0</td>
<td>2371</td>
</tr>
<tr class="even">
<td>2007-2008</td>
<td>0.7</td>
<td>0.7</td>
<td>5.1</td>
<td>53.8</td>
<td>39.7</td>
<td>100.0</td>
<td>1725</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>0.6</strong></td>
<td><strong>1.0</strong></td>
<td><strong>4.5</strong></td>
<td><strong>62.3</strong></td>
<td><strong>31.6</strong></td>
<td><strong>100.0</strong></td>
<td>4096</td>
</tr>
</tbody>
</table>
<p>In the period 1989-1994 SDLP was the primary nationalist political party, Sinn Fein being the more republican of the two parties. In Breen, 96 per cent of Sinn Fein voters suggest support for a United Ireland, as opposed to 76 per cent in the case of the SDLP. Maintaining for many years controversial ties to the IRA Sinn Fein was estranged from the peace process. Even up until 1994, the party was reluctant to participate in cross-community debate. After 1996, Sinn Fein became more established as a mainstream political party. By 2001 Sinn Fein and the SDLP were virtually neck and-neck but Sinn Fein had significantly greater momentum and by 2005 had outstripped the SDLP as the nationalist voting stronghold.<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a><a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a> Table 5, however, implies overwhelming support for the SDLP, with 62.7 per cent of support between 2000 and 2004 and 53.8 per cent in 2007-08. This may explain the more moderate attitude towards devolution highlighted in Table 2. It also throws up concerns over how representative the sample is as well. Another possible explanation may be that, having conducted the interviews face-to-face, people were reluctant to express support for Sinn Fein, consider its more explicitly republican connotations.</p>
<p>The shifting in allegiances between 2000 and 2008 may be seen as representative of Sinn Fein’s growing recognition as a mainstream political party. That there is a shift in both the SDLP (decline) and Sinn Fein (increase) suggests that, under-representation notwithstanding, considering the separate analysis of the party’s support, there is a compelling trend at play. Therefore, what we have is both an indication of a shift in preference towards the more republican of the two parties, at the same time as increased willingness to accept a devolved government. And, perhaps, this is the crucial distinction; that of support for a devolved government rather than Home Rule: compromise is acceptable as long as people feel empowered by a sense of autonomy and by a vociferous figurehead. This is illustrated perfectly by then-contemporaneous events.</p>
<p>The power-sharing of 2006 saw a union between Northern Ireland’s two most polarized political parties, neither of whom had featured in Northern Ireland’s first assembly back in 1998, just after the Good Friday Agreement. Then, it was the more moderate UUP and SDLP who were chosen as representatives. Nine years later, the responsibility of finding compromise was entrusted to the DUP and Sinn Fein. Their acrimony was subjugated by the mutual desire for autonomy. Sinn Fein rejected roles in the shadow assembly, and formed an alliance with their local rivals because they would only participate in a devolved power-sharing government, irrespective, ultimately, of who they would be sharing power with.<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a></p>
</section>
<section id="table-6-catholics-constitutional-identity-by-party-preference" class="level3">
<h3 class="anchored" data-anchor-id="table-6-catholics-constitutional-identity-by-party-preference">Table 6: Catholics: Constitutional Identity by Party Preference (%)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Party</th>
<th>Remain part of UK (%)</th>
<th>Reunify Ireland (%)</th>
<th>Other option (%)</th>
<th>Don’t know (%)</th>
<th>Total (%)</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2000-2004</td>
<td>SDLP</td>
<td>20.9</td>
<td>48.6</td>
<td>13.7</td>
<td>16.8</td>
<td>100.0</td>
<td>1930</td>
</tr>
<tr class="even">
<td>2007-2008</td>
<td>SDLP</td>
<td>54.0</td>
<td>33.4</td>
<td>8.7</td>
<td>3.9</td>
<td>100.0</td>
<td>689</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>SDLP</strong></td>
<td><strong>27.6</strong></td>
<td><strong>45.5</strong></td>
<td><strong>12.7</strong></td>
<td><strong>14.2</strong></td>
<td><strong>100.0</strong></td>
<td>2619</td>
</tr>
<tr class="even">
<td>2000-2004</td>
<td>Sinn Fein</td>
<td>5.4</td>
<td>80.1</td>
<td>7.7</td>
<td>6.8</td>
<td>100.0</td>
<td>977</td>
</tr>
<tr class="odd">
<td>2007-2008</td>
<td>Sinn Fein</td>
<td>20.5</td>
<td>67.4</td>
<td>10.8</td>
<td>1.4</td>
<td>100.0</td>
<td>288</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>Sinn Fein</strong></td>
<td><strong>9.8</strong></td>
<td><strong>76.4</strong></td>
<td><strong>8.6</strong></td>
<td><strong>5.2</strong></td>
<td><strong>100.0</strong></td>
<td>1265</td>
</tr>
</tbody>
</table>
<p>Chi-Square Tests</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 41%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Party</th>
<th>Test</th>
<th>Value</th>
<th>df</th>
<th>Asymp. Sig. (2-sided)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SDLP</td>
<td>Pearson Chi-Square</td>
<td>181.793</td>
<td>3</td>
<td>0.000</td>
</tr>
<tr class="even">
<td></td>
<td>Likelihood Ratio</td>
<td>175.760</td>
<td>3</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td></td>
<td>Linear-by-Linear Association</td>
<td>133.305</td>
<td>1</td>
<td>0.000</td>
</tr>
<tr class="even">
<td></td>
<td>N of Valid Cases</td>
<td>1930</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Sinn Fein</td>
<td>Pearson Chi-Square</td>
<td>65.269</td>
<td>3</td>
<td>0.000</td>
</tr>
<tr class="even">
<td></td>
<td>Likelihood Ratio</td>
<td>63.116</td>
<td>3</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td></td>
<td>Linear-by-Linear Association</td>
<td>27.692</td>
<td>1</td>
<td>0.000</td>
</tr>
<tr class="even">
<td></td>
<td>N of Valid Cases</td>
<td>977</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Table 7 illustrates the trust people placed in the most hard-line of parties to fight their corner, while also highlighting a growing recognition that this battle will take place, fundamentally, at a Northern Irish level. Perhaps even it is a rebuttal of subservience under both direct rule and the union with Ireland, wherein local voices may resonate less strongly than in the cloistered environment of Northern Ireland. Regardless of whether people like to admit it, it may reflect some bizarre sense of Northern Irish patriotism, the recognition and entrenchment of polar identities within a workable framework, with just the right balance of autonomy and management. In a divided society with a degree of autonomy, it becomes important to achieve ‘critical mass’ in negotiating with the ‘other’ side for a ‘fair’ slice of the pie (that is, resource allocation decisions). Sinn Fein are the party that Catholics now view as the one to shout loudest for their share of the pie, just as Protestants seem to have decided on the DUP.</p>
</section>
<section id="table-7-2007-2008-catholics-preferred-long-term-policy-for-ni-by-ns-sec-5-class-definitions" class="level3">
<h3 class="anchored" data-anchor-id="table-7-2007-2008-catholics-preferred-long-term-policy-for-ni-by-ns-sec-5-class-definitions">Table 7: 2007-2008 Catholics: Preferred Long-Term Policy for NI by NS-SEC 5-Class Definitions</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 9%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>Class</th>
<th>Direct Rule (%)</th>
<th>Devolution (%)</th>
<th>Reunify Ireland (%)</th>
<th>Total (%)</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Managerial &amp; professional occupations</td>
<td>2.4</td>
<td>51.7</td>
<td>45.9</td>
<td>100.0</td>
<td>403</td>
</tr>
<tr class="even">
<td>Intermediate</td>
<td>9.3</td>
<td>47.7</td>
<td>43.0</td>
<td>100.0</td>
<td>430</td>
</tr>
<tr class="odd">
<td>Small employers &amp; own account workers</td>
<td>4.3</td>
<td>39.1</td>
<td>56.5</td>
<td>100.0</td>
<td>91</td>
</tr>
<tr class="even">
<td>Lower supervisory &amp; technical</td>
<td>11.3</td>
<td>38.7</td>
<td>50.0</td>
<td>100.0</td>
<td>62</td>
</tr>
<tr class="odd">
<td>Semi-routine &amp; routine</td>
<td>6.0</td>
<td>36.5</td>
<td>57.5</td>
<td>100.0</td>
<td>125</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>5.6</strong></td>
<td><strong>42.8</strong></td>
<td><strong>51.6</strong></td>
<td><strong>100.0</strong></td>
<td>711</td>
</tr>
</tbody>
</table>
<p>Chi-Square Tests</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Test</th>
<th>Value</th>
<th>df</th>
<th>Asymp. Sig. (2-sided)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pearson Chi-Square</td>
<td>21.756</td>
<td>8</td>
<td>0.005</td>
</tr>
<tr class="even">
<td>Likelihood Ratio</td>
<td>21.569</td>
<td>8</td>
<td>0.006</td>
</tr>
<tr class="odd">
<td>Linear-by-Linear Association</td>
<td>6.864</td>
<td>1</td>
<td>0.009</td>
</tr>
<tr class="even">
<td>N of Valid Cases</td>
<td>711</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Most evident in the table above is that support for a reunified Ireland is concentrated among the lowest three classes, all of whom express at least 50 per cent support for a United Ireland. Between the semi-routine worker and the managerial and professional occupations there is a differential of 11.6 per cent. This would appear to support the assertion that expressions of constitutional identity are influenced, at least to some degree by social class. Similarly, it is important to note that devolution is more heavily favoured by the top two strata. In fact, support for devolution can be seen to correlate entirely with social classification. I can only infer, then, that those at the top of the pile wish to see no change to their position and are, in the majority, content to see Union with Britain via devolution so long as they are succeeding.</p>
<p>One very interesting finding is the surprising degree of support for Direct Rule among those in Lower supervisory and technical occupations, with 11.3 per cent, as well as, to a lesser extent those in intermediate and routine positions. Owing to their greater expressions of support for a unified Ireland one would have assumed, perhaps, that religiosity was simply more entrenched among lower and middling class positions. However, what this suggests instead is that, while a Unified Ireland may best serve their interests, fundamentally, these groups are simply seeking a change in their circumstances and will take improvement wherever they can find it. Indeed, self-employed workers present an anomaly; perhaps explicable by their stronger desire for self-determination.</p>
<p>All in all, social class suggests that identity in Northern Ireland is dependent on more than merely religion. It is holistic and entails the evolution of a class-based interaction with religion which has been eroded and re-assessed in recent years. In Breen the repudiation of the union is significantly more unanimous and so, while my own findings align to an extent with his hypothesis that ‘strength of Nationalist feeling depends less on whether a Catholic is well-educated, middle class and so on and more on the degree to which he or she thinks that Catholics are discriminated in Northern Ireland’[22], there are numerous caveats.</p>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>I believe that within Table 7 lies some explanation for the curiosity that is a strengthening in extremist politics coinciding with a moderation in constitutional preferences. Social class highlights the fact that the new expressions of identity relate to satisfaction with the status quo and the extent to which people feel their needs are being met. Support for a united Ireland is far from universal; in his conclusion Breen shoots down the prospect of its enactment, arguing that it would take an adult Catholic population ‘two and a half times larger than the Protestant population’. It is perhaps indicative both of the social gains made by Catholics as well as the recognition of its implausibility that has ensured that expressions of identity are being re-directed to maximizing the stake in whatever semblance of autonomy can be grasped at. Devolution in Northern Ireland represents the bare minimum, but it is enough to establish a rarefied, insular environment in which interest groups can compete and thrive. This is the realization of Rose’s demonstration of Ulster as a separate entity, where identities which would go ignored in a larger setting are the drivers of change.</p>
<p>I am inclined to reject the null hypotheses. Religiosity is subjugated, therefore, to a desire for advancement of particular social compositions rendered immovable by history. Catholics and Protestants defy religion; they are social and cultural identities to the extent that political parties are entrenched along religious grounds, with an in-between ignored by the voters because it obfuscates the advancement of your interests. This is the conclusion I have drawn from the inconsistencies noted between Tables 4 and Tables 5, which highlighted the discrepancy between constitutional identification and voting patterns. In the recognition of a need to negotiate with the other side it is uncertainty that drives people to the extremes. Sinn Fein, as the most vociferous of these on the Nationalist side, are charged then with the subliminal formation of a new identity; a more modern, realistic expression of nationalism, that of a new, Catholic unionism; safeguarding and consolidating the Catholic demographic. It an identity filtered through an innate recognition that cross-community exchange is essential, but manifests itself as a monument to the lack of trust engendered by years of conflict. This ensures that those of each side demand figures of especially explosive common identity to stand their ground for them; it is balance and advancement through peaceful hostilities. In the wake of World War I, Winston Churchill referred to the prospects of change in Northern Ireland with uncompromising pessimism:</p>
<p>Every institution in the world was strained. Great Empires have been overturned. The whole map of Europe has been changed… But as the deluge subsides and the waters fall short, we see the dreary steeples of Fermanagh and Tyrone emerging once again. The integrity of their quarrel is one of the few institutions that has been unaltered in the cataclysm which has swept the world.[23]</p>
<p>In fact, with a shift in the Catholic proportion favouring a union there is a change. The extent to which this is a consequence of the change in wording cannot disguise the fact that there has been an evolution in the way in which priorities are expressed. New wording merely masks the development of this phenomenon. This shift certainly demands further exploration, more than my research had the resources to afford it, but I believe that, rooted within social class, a common ground is developing, with identities enforced more by socio-political necessity as a consequence of affiliation not merely to religion, but to a more powerful, holistic, deep-seated identity. This subject demands more immersive research and, given the unprecedented political changes, will certainly get it.</p>
</section>
<section id="bibliography" class="level2">
<h2 class="anchored" data-anchor-id="bibliography">Bibliography</h2>
<p>Breen, Richard, ‘Who Wants a United Ireland? Constitutional Preferences among Catholics and Protestants’, in Richard Breen, Paula Devine and Lizanne Dowds (eds.), <em>Social Attitudes in Northern Ireland: The Fifth Report 1995-1996</em> (Belfast, 1996).</p>
<p>Moxon-Browne, Edward, ‘National Identity in Northern Ireland’, in Peter Stringer and Gillian Robinson (eds.), <em>Social Attitudes in Northern Ireland: The First Report</em> (Belfast, 1991). Available online at: <a href="http://cain.ulst.ac.uk/othelem/research/nisas/rep1c2.htm#chap2">http://cain.ulst.ac.uk/othelem/research/nisas/rep1c2.htm#chap2</a> (accessed 22 December 2009).</p>
<p>Rose, Richard, <em>Governing Without Consensus: An Irish Perspective</em> (London, 1971).</p>
<p>Whyte, John, <em>Interpreting Northern Ireland</em> (New York, 1990).</p>
<section id="web-resources" class="level3">
<h3 class="anchored" data-anchor-id="web-resources">Web Resources:</h3>
<ul>
<li><a href="http://www.ark.ac.uk/elections/">http://www.ark.ac.uk/elections/</a></li>
<li><a href="http://cain.ulst.ac.uk/">http://cain.ulst.ac.uk/</a></li>
<li><a href="http://www.csu.nisra.gov.uk/survey.asp77.htm">http://www.csu.nisra.gov.uk/survey.asp77.htm</a></li>
<li><a href="http://www.data-archive.ac.uk/">http://www.data-archive.ac.uk/</a></li>
<li><a href="http://www.niassembly.gov.uk/io/summary/new_summary.htm">http://www.niassembly.gov.uk/io/summary/new_summary.htm</a></li>
<li><a href="http://www.ons.gov.uk/about-statistics/classifications/current/ns-sec/index.html">http://www.ons.gov.uk/about-statistics/classifications/current/ns-sec/index.html</a></li>
<li><a href="http://www.rte.ie/news/2006/0902/northpolitics.html?rss">http://www.rte.ie/news/2006/0902/northpolitics.html?rss</a></li>
</ul>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Richard Breen, ‘Who Wants a United Ireland? Constitutional Preferences among Catholics and Protestants’, in Richard Breen, Paula Devine and Lizanne Dowds (eds.), <em>Social Attitudes in Northern Ireland: The Fifth Report 1995-1996</em> (Belfast, 1996).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Ibid, p.33.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>BBC, available online at: <a href="http://news.bbc.co.uk/1/hi/northern_ireland/8457650.stm">http://news.bbc.co.uk/1/hi/northern_ireland/8457650.stm</a> (accessed 23 May 2010).<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Richard Rose, <em>Governing Without Consensus: An Irish Perspective</em> (London, 1971).<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>John Whyte, <em>Interpreting Northern Ireland</em> (New York, 1990).<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Edward Moxon-Browne, ‘National Identity in Northern Ireland’, in Peter Stringer and Gillian Robinson (eds.), <em>Social Attitudes in Northern Ireland: The First Report</em> (Belfast, 1991). Available online at: <a href="http://cain.ulst.ac.uk/othelem/research/nisas/rep1c2.htm#chap2">http://cain.ulst.ac.uk/othelem/research/nisas/rep1c2.htm#chap2</a> (accessed 22 December 2009).<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Coalitions are formed on the basis that the largest party has First Minister, second largest has deputy First Minister. See: <a href="http://www.niassembly.gov.uk/io/summary/new_summary.htm">http://www.niassembly.gov.uk/io/summary/new_summary.htm</a>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>A comparison of the 1992 Elections against those of 2010 supports this claim, demonstrating the moves from SDLP to Sinn Fein and from the UUP to the DUP. See: <a href="http://www.ark.ac.uk/elections/">http://www.ark.ac.uk/elections/</a>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Richard Breen, ‘Who Wants a United Ireland? Constitutional Preferences among Catholics and Protestants’, p.34.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Available online at: <a href="http://cain.ulst.ac.uk/othelem/research/nisas/nisas.htm">http://cain.ulst.ac.uk/othelem/research/nisas/nisas.htm</a>.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Available online at: <a href="http://www.ark.ac.uk/nilt/">http://www.ark.ac.uk/nilt/</a>.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Accessed at: <a href="https://www.data-archive.ac.uk/findingData/snDescription.asp?sn=5348">https://www.data-archive.ac.uk/findingData/snDescription.asp?sn=5348</a>.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>Available online at: <a href="http://www.ark.ac.uk/nilt/2008/tech08.pdf">http://www.ark.ac.uk/nilt/2008/tech08.pdf</a>.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>For a discussion of how this works see: <a href="http://www.csu.nisra.gov.uk/survey.asp77.htm">http://www.csu.nisra.gov.uk/survey.asp77.htm</a>.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>NILT questionnaire.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>Richard Breen, ‘Who Wants a United Ireland? Constitutional Preferences among Catholics and Protestants’, pp.41-43.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>See: <a href="http://www.ons.gov.uk/about-statistics/classifications/current/ns-sec/index.html">http://www.ons.gov.uk/about-statistics/classifications/current/ns-sec/index.html</a>.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>Available online at: <a href="http://www.ark.ac.uk/elections/fw01.htm">http://www.ark.ac.uk/elections/fw01.htm</a>.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>Available online at: <a href="http://cain.ulst.ac.uk/issues/politics/election/electsum.htm">http://cain.ulst.ac.uk/issues/politics/election/electsum.htm</a>.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>See: <a href="http://www.rte.ie/news/2006/0902/northpolitics.html?rss">http://www.rte.ie/news/2006/0902/northpolitics.html?rss</a>.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    window.setColorSchemeToggle(window.hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/diggydigsdata\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>This page is built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/diggydigsdata/blob/main/2010-05-01-determinants-of-national-identity-in-northern-ireland.md" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="./LICENSE.md">
<p>License</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>