<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.28">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-04-18">

<title>DRAFT: Post-Relegation Attendance Churn – Diggy Digs Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./assets/img/favicons/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-013882879a21c3ca3416aac467d3c23f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-013882879a21c3ca3416aac467d3c23f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-013882879a21c3ca3416aac467d3c23f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1e0d785306329dd87d93ab7c32bdc37a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-f6530c4cab28cdaa8f4f88d19fa58afb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-1e0d785306329dd87d93ab7c32bdc37a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta property="og:title" content="DRAFT: Post-Relegation Attendance Churn – Diggy Digs Data">
<meta property="og:description" content="">
<meta property="og:site_name" content="Diggy Digs Data">
</head>

<body class="nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    window.setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      window.setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    window.hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(darkModeDefault) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const darkModeDefault = false;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !window.hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
    };
    // Switch to dark mode if need be
    if (window.hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./assets\img\brand.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Diggy Digs Data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">Analytics</span>
    </span>
  </li>  
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">Tutorials</span>
    </span>
  </li>  
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">Reviews</span>
    </span>
  </li>  
  <li class="nav-item">
    <span class="nav-link">
<span class="menu-text">Upcomings</span>
    </span>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/diggydigsdata"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DRAFT: Post-Relegation Attendance Churn</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Football</div>
    <div class="quarto-category">Attendances</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 18, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>I’m a Burnley fan. And in honour of our impending promotion to the Premier League and consolidation as a yoyo club par excellence, I thought it would be a good time to assess the impact of relegation from the Premier League on attendance figures. Because it’s never too early to plan ahead.</p>
<section id="yoyo-club-rankings" class="level3">
<h3 class="anchored" data-anchor-id="yoyo-club-rankings">Yoyo Club Rankings</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 19%">
<col style="width: 31%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Club</th>
<th>PL Relegations</th>
<th>Championship Promotions</th>
<th>Current League</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Norwich City</td>
<td>6</td>
<td>5</td>
<td>Championship</td>
</tr>
<tr class="even">
<td>West Bromwich Albion</td>
<td>5</td>
<td>5</td>
<td>Championship</td>
</tr>
<tr class="odd">
<td>Burnley</td>
<td>4</td>
<td>5</td>
<td>Premier League</td>
</tr>
<tr class="even">
<td>Leicester City</td>
<td>5</td>
<td>5</td>
<td>Championship</td>
</tr>
<tr class="odd">
<td>Crystal Palace</td>
<td>4</td>
<td>4</td>
<td>Premier League</td>
</tr>
<tr class="even">
<td>Middlesbrough</td>
<td>4</td>
<td>4</td>
<td>Championship/TBD</td>
</tr>
<tr class="odd">
<td>Sunderland</td>
<td>4</td>
<td>4</td>
<td>Championship/TBD</td>
</tr>
<tr class="even">
<td>Watford</td>
<td>4</td>
<td>4</td>
<td>Championship</td>
</tr>
<tr class="odd">
<td>Sheffield United</td>
<td>4</td>
<td>3</td>
<td>Championship/TBD</td>
</tr>
<tr class="even">
<td>Southampton</td>
<td>3</td>
<td>2</td>
<td>Championship</td>
</tr>
</tbody>
</table>
<p>Incidentally, Leicester’s recent relegation not only brings them into second place on the Premier League relegation rankings but pulls them clear of Birmingham atop the Top-Flight relegations table with 13.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<p>For this project, I gathered attendance data for every relegated club in the season they were relegated, and in the 2 seasons following their relegation. I also checked what league they were in for their 2nd year post-relegation. Had they been promoted at the first attempt? Spent another season in the Championship, or plummeted into League 1. I gathered all of this data from <a href="https://www.european-football-statistics.co.uk/index1.htm">European-Football-Statistics.co.uk</a>.</p>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<section id="increased-attendance-after-relegation" class="level3">
<h3 class="anchored" data-anchor-id="increased-attendance-after-relegation">Increased attendance after relegation?</h3>
<p>Let’s start on a positive note. On 10 occasions, teams managed to increase their average attendance following relegation.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 23%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Relegated Team (Season)</th>
<th>Attd.</th>
<th>Year After</th>
<th>Attd. year after</th>
<th>Loss/Gain %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sunderland (96/97)</td>
<td>20,865</td>
<td>1997-98</td>
<td>33,492</td>
<td>60.5%</td>
</tr>
<tr class="even">
<td>Leicester City (01/02)</td>
<td>19,835</td>
<td>2002-03</td>
<td>29,231</td>
<td>47.4%</td>
</tr>
<tr class="odd">
<td>Nottingham Forest (92/93)</td>
<td>21,910</td>
<td>1993-94</td>
<td>23,051</td>
<td>5.2%</td>
</tr>
<tr class="even">
<td>Ipswich Town (01/02)</td>
<td>24,426</td>
<td>2002-03</td>
<td>25,455</td>
<td>4.2%</td>
</tr>
<tr class="odd">
<td><strong>Burnley</strong> (21/22)</td>
<td>19,399</td>
<td>2022-23</td>
<td>19,953</td>
<td>2.9%</td>
</tr>
<tr class="even">
<td>Newcastle United (15/16)</td>
<td>49,754</td>
<td>2016-17</td>
<td>51,106</td>
<td>2.7%</td>
</tr>
<tr class="odd">
<td>Norwich City (04/05)</td>
<td>24,350</td>
<td>2005-06</td>
<td>24,952</td>
<td>2.5%</td>
</tr>
<tr class="even">
<td>Crystal Palace (94/95)</td>
<td>14,992</td>
<td>1995-96</td>
<td>15,248</td>
<td>1.7%</td>
</tr>
<tr class="odd">
<td>Luton Town (23/24)</td>
<td>11,244</td>
<td>2024-25</td>
<td>11,420</td>
<td>1.6%</td>
</tr>
<tr class="even">
<td>Middlesbrough (96/97)</td>
<td>29,848</td>
<td>1997-98</td>
<td>29,994</td>
<td>0.5%</td>
</tr>
</tbody>
</table>
<p>And I have to give a shoutout to Burnley and, indeed, to Vincent Kompany because he certainly galvanised the supporters that season.</p>
<p>A couple teams really jump out. Both Sunderland and Leicester City moved into new stadia the year after their relegation, and this gave them a considerable bump. They must have been absolutely packing out their stadia the season prior and had supporters banging down the doors to get in. Sunderland even managed to add over 5,000 supporters to their tally the season after relegation, despite the fact that they were still stuck in the Championship. Leicester also increased attendances in 2003-04, by 1,600 to 30,983. But they spent that season in the Premier League, so it’s less startling to see an increase.</p>
<p>Newcastle also catch the eye. 51,106 fans during the 2016-17 is quite extraordinary. Newcastle’s fanbase has a reputation for diehard loyalty. It’s why many neutrals were happy to see them bought by the Saudis, despite misgivings about sportwashing. Indeed, Newcastle also have the second-highest post-relegation attendance - 43,388 during the 2009-2010 season. That particular season did see an 11% drop on the previous year’s PL average. And the contrast between 2016-17 and 2009-10 is enlightening. Similar to how Burnley fell under the spell of Vincent Kompany in 2022/23, Newcastle fans had a great relationship with Rafael Benitez - their manager from 2016 to 2019. Hired towards the end of their 2015/16 relegation season, it was considered quite a coup to attract Benitez to a Championship-bound club. And the fans showed their appreciation during his first full season in charge with record-breaking attendances.</p>
<p>Typically, we start to see the cracks in season 2 outside the top flight. Filtering out teams like Leicester who were promoted at the first attempt and had Premier League fixtures to pull in the fans, only 6 teams see attendance figures in the black by season 2.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 6%">
<col style="width: 17%">
<col style="width: 11%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Relegated Team (Season)</th>
<th>Attd.</th>
<th>Attd. year after</th>
<th>Loss/Gain %</th>
<th>Attd. 2 yrs. after</th>
<th>Loss/Gain % 2 yrs.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sunderland (96/97)</td>
<td>20,865</td>
<td>33,492</td>
<td>60.5%</td>
<td>38,745</td>
<td>86%</td>
</tr>
<tr class="even">
<td>Middlesbrough (92/93)</td>
<td>16,724</td>
<td>10,400</td>
<td>-37.8%</td>
<td>18,702</td>
<td>11.8%</td>
</tr>
<tr class="odd">
<td>Crystal Palace (94/95)</td>
<td>14,992</td>
<td>15,248</td>
<td>1.7%</td>
<td>16,085</td>
<td>7.3%</td>
</tr>
<tr class="even">
<td>Manchester City (95/96)</td>
<td>27,869</td>
<td>26,753</td>
<td>-4.0%</td>
<td>28,196</td>
<td>1.2%</td>
</tr>
<tr class="odd">
<td>Norwich City (04/05)</td>
<td>24,350</td>
<td>24,952</td>
<td>2.5%</td>
<td>24,545</td>
<td>0.8%</td>
</tr>
<tr class="even">
<td>Ipswich Town (01/02)</td>
<td>24,426</td>
<td>25,455</td>
<td>4.2%</td>
<td>24,520</td>
<td>0.4%</td>
</tr>
</tbody>
</table>
<p>Again, we have some anomalies. Middlesborough’s attendance nosedived in 1993-94 but they were undergoing a stadium rebuild. Basically, they had more stadium 2 years later. By 2017-18, Middlesborough were hosting 25,544 fans a game in the Championship and over 30,000 during their stint for the preceding year’s stint in the Prem. So their 10,400 fan turnout - heck, even their 18,702 fan turnout, are merely reflective of stadium constraints and not reflective of their true fanbase.</p>
</section>
<section id="nosedives" class="level3">
<h3 class="anchored" data-anchor-id="nosedives">Nosedives</h3>
<p>middlesborough, oldham</p>
</section>
<section id="and-in-general" class="level3">
<h3 class="anchored" data-anchor-id="and-in-general">And in general?</h3>
<p>On average, attendance falls significantly after relegation. The below table shows a 1st-year average decrease of 13.72%. And it shows that in the second year, there is an average decrease of 12.34%.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 38%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>League</th>
<th>Year After Avg. Loss/Gain %</th>
<th>2 yrs After Avg. of Loss/Gain %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Championship</td>
<td>-13.72%</td>
<td>-19.15%</td>
</tr>
<tr class="even">
<td>League 1</td>
<td>N/A</td>
<td>-23.80%</td>
</tr>
<tr class="odd">
<td>PL</td>
<td>N/A</td>
<td>5.36%</td>
</tr>
<tr class="even">
<td>Overall</td>
<td>-13.72%</td>
<td>-12.34%</td>
</tr>
</tbody>
</table>
<p>EXCLUDING MIDDLESBOROUGH, LEICESTER &amp; SUNDERLAND</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 38%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>League</th>
<th>Year After Avg. Loss/Gain %</th>
<th>2 yrs After Avg. of Loss/Gain %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Championship</td>
<td>-13.45%</td>
<td>-21.49%</td>
</tr>
<tr class="even">
<td>League 1</td>
<td>N/A</td>
<td>-23.80%</td>
</tr>
<tr class="odd">
<td>PL</td>
<td>N/A</td>
<td>3.24%</td>
</tr>
<tr class="even">
<td>Overall</td>
<td>-14.98%</td>
<td>-14.59%</td>
</tr>
</tbody>
</table>
<p>I think this table excluding Middlesborough, Leicester and Sunderland who introduce anomalies related to stadium constructions may be a better reference for this data. Superficially, the above data is reassuring. If you just look at the overalls, then it would seem attendances stabilise in Year 2 after relegation. You lose 15% of your attendance immediately after relegation, but at least it doesn’t get worse. But it does.</p>
<p>If you didn’t get promoted to the Premier League at the first time of asking and spend a 2nd year in the Championship, then you can expect to lose a further 8% of your Premier League attendance. And if you get relegated to League 1, that jumps above 10%. So it seems teams will stick with a team more resolutely in the year after their relegation, likely hoping for a successful season and a swift return. By Year 2, that optimism may fade and attendance figures dwindle still further. Let’s probe that performance factor further.</p>
</section>
<section id="does-performance-affect-attendance" class="level3">
<h3 class="anchored" data-anchor-id="does-performance-affect-attendance">Does performance affect attendance?</h3>
<p>The below table shows how the outcome of your first season post-relegation can impact attendance figures during that season.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Destination during Championship Season</th>
<th>Average of Loss/Gain %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Championship</td>
<td>-16.58%</td>
</tr>
<tr class="even">
<td>League 1</td>
<td>-28.16%</td>
</tr>
<tr class="odd">
<td>PL</td>
<td>-5.84%</td>
</tr>
<tr class="even">
<td>2023/24 teams without year 2 data</td>
<td>-4.07%</td>
</tr>
<tr class="odd">
<td>&nbsp;&nbsp;&nbsp;Burnley</td>
<td>-7.29%</td>
</tr>
<tr class="even">
<td>&nbsp;&nbsp;&nbsp;Luton Town</td>
<td>1.57%</td>
</tr>
<tr class="odd">
<td>&nbsp;&nbsp;&nbsp;Sheffield United</td>
<td>-6.47%</td>
</tr>
</tbody>
</table>
<p>EXCLUDING MIDDLESBOROUGH (93/94), LEICESTER (02/03) &amp; SUNDERLAND (97/98)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Destination during Championship Season</th>
<th>Average of Loss/Gain %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Championship</td>
<td>-17.53%</td>
</tr>
<tr class="even">
<td>League 1</td>
<td>-28.16%</td>
</tr>
<tr class="odd">
<td>PL</td>
<td>-8.15%</td>
</tr>
<tr class="even">
<td>2023/24 teams with unknown destination</td>
<td>-4.07%</td>
</tr>
<tr class="odd">
<td>&nbsp;&nbsp;&nbsp;Burnley</td>
<td>-7.29%</td>
</tr>
<tr class="even">
<td>&nbsp;&nbsp;&nbsp;Luton Town</td>
<td>1.57%</td>
</tr>
<tr class="odd">
<td>&nbsp;&nbsp;&nbsp;Sheffield United</td>
<td>-6.47%</td>
</tr>
</tbody>
</table>
<p>If your club isn’t on track to bounce straight back, then they can expect to lose around 17% of the previous years’ attendance. And if they are heading for back-to-back relegations, with a freefall to League 1, expect losses of 28.16%. If, however, they are in the hunt for promotion then the losses are considerably less. Teams bound for the Premier League only lose 5.84% (8.15% excluding the new-stadium teams). As you can see, the above data also excludes teams who were relegated in 2023/24 - Burnley, Luton, Sheffield United. However, I think it’s best to include them. Luton are likely to be relegated, Burnley are likely to be promoted, and Sheffield United will probably just miss out on the top 2 and console themselves with the playoffs. Since all 3 clubs have spent the entire season on these trajectories, it’s safe enough to incorporate their impact on the season’s attendances. So I will include them as Luton: relegated to League 1; Burnley and Sheffield United promoted to the Premier League.</p>
<p>With Burnley &amp; Sheffield United as PL, and Luton as League 1</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Destination during Championship Season</th>
<th>Average of Loss/Gain %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overall</td>
<td>-13.72%</td>
</tr>
<tr class="even">
<td>Championship</td>
<td>-16.58%</td>
</tr>
<tr class="odd">
<td>League 1</td>
<td>-20.73%</td>
</tr>
<tr class="even">
<td>PL</td>
<td>-5.92%</td>
</tr>
<tr class="odd">
<td>Grand Total</td>
<td>-13.72%</td>
</tr>
</tbody>
</table>
<p>With Burnley &amp; Sheffield United as PL, and Luton as League 1. EXCLUDING MIDDLESBOROUGH (93/94), LEICESTER (02/03) &amp; SUNDERLAND (97/98)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Destination during Championship Season</th>
<th>Average of Loss/Gain %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overall</td>
<td>-14.98%</td>
</tr>
<tr class="even">
<td>Championship</td>
<td>-17.53%</td>
</tr>
<tr class="odd">
<td>League 1</td>
<td>-20.73%</td>
</tr>
<tr class="even">
<td>PL</td>
<td>-8.05%</td>
</tr>
<tr class="odd">
<td>Grand Total</td>
<td>-14.98%</td>
</tr>
</tbody>
</table>
<p>Luton really buck the trend for League 1-destined sides. And because there are so few teams who are relegated from the Premier League to League 1 in consecutive seasons, their outlier status has a huge impact on the data, dropping the averages by almost 8%. But can Luton really be considered anomalous when the data population is so small? In my view, yes. First of all, Luton had an emotional relegation season. Their captain Tom Lockyer suffered a cardiac arrest mid-game. Fortunately, he survived and has been on a road to recovery ever since with the view to playing again. Moreover, Luton battled very bravely against relegation despite these traumatising events and despite being financial minnows. Luton were a uniquely united club during their relegation season. However, that is not the only explanation. The other is that Luton are another stadium-constrained side. Kenilworth Road is famously tiny, and was a peculiar relic among Premier League stadiums. Luton have received approval for a stadium rebuild that will double its capacity. Based on their increased attendances post-relegation, Luton are another case of a club where demand has exceeded supply for some time.</p>
<p>Just a quick note on Burnley, who were in the black during their Kompany-led campaign but have lost almost 8% this season. There are a few factors at play. First, morale sank during Kompany’s PL season. Burnley were truly awful and the core of their Championship-winning side was cast aside in favour of new recruits - an inexplicable decision in the view of many fans. Moreover, ALK capital - the ownership group - made some ill-judged and patronising comments to supporters for not bringing a positive enough atmosphere to Turf Moor. In a nutshell, the mood was bleak by the end of 2022-23. Kompany’s departure and subsequent replacement by Scott Parker failed to excite fans. Nor did selling half the first team squad and sitting through a million 0-0 draws. Despite the successful campaign, Parker-ball has been a bit of a slog. Sidenote: I was a huge Parker skeptic at first but I think he has brought the solidity Burnley needed and, as the season has gone on, a more cohesive team has taken shape, the football has yielded more goals and the fanbase has gotten on side. In any case, this all goes to highlight that there are complexities behind the averages I am presenting here.</p>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<ul>
<li>Teams can typically expect to lose 12 to 15% of their attendance after relegation</li>
<li>If you are on track for Promotion, these losses are lessened</li>
<li>If you are on track to stay in the Championship, these losses are slightly higher</li>
<li>And if you are on track for League 1, these losses are considerably higher</li>
<li>Investigating the outliers in the dataset tends to reveal mitigating circumstances. Often these relate to stadium builds, but in other cases - like Newcastle and Burnley - it is just vibes at play. To really understand the data I would dig into each relegated team a little more to understand what underlying factors affect other teams because it’s possibly more nuanced than relegation = fanbandonment.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    window.setColorSchemeToggle(window.hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/diggydigsdata\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>This page is built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/diggydigsdata/blob/main/2025-04-18-post-relegation-attendance-churn.md" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="./LICENSE.md">
<p>License</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>