<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.28">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Diggy">
<meta name="dcterms.date" content="2025-11-01">
<meta name="description" content="Dishing the data dirt on post-relegation loyalty.">

<title>Fair-Weather Fans? – Diggy Digs Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/img/favicons/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-013882879a21c3ca3416aac467d3c23f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-013882879a21c3ca3416aac467d3c23f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-013882879a21c3ca3416aac467d3c23f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ea6dcb636b98e4259611748ef6731b59.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-dd122c0da25c9fd53758c928d9b42162.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-ea6dcb636b98e4259611748ef6731b59.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-HNQKPVKC29"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-HNQKPVKC29', { 'anonymize_ip': true});
</script>


<meta property="og:title" content="Fair-Weather Fans? – Diggy Digs Data">
<meta property="og:description" content="Dishing the data dirt on post-relegation loyalty.">
<meta property="og:image" content="https://diggydigsdata.github.io/posts/post-relegation-attendance/featured.jpg">
<meta property="og:site_name" content="Diggy Digs Data">
<meta property="og:image:alt" content="A picture of Stadion Za Lužánkami, formerly the 50,000 capacity home ground of Zbrojovka Brno, and now an overgrown jungle.">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    window.setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      window.setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    window.hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(darkModeDefault) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const darkModeDefault = false;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !window.hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
    };
    // Switch to dark mode if need be
    if (window.hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets\img\brand.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Diggy Digs Data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/diggydigsdata"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:diggydigsdata@gmail.com"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/eoindignan1989/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Fair-Weather Fans?</h1>
                  <div>
        <div class="description">
          Dishing the data dirt on post-relegation loyalty.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Football</div>
                <div class="quarto-category">Analytics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Diggy </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">November 1, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#yoyometer" id="toc-yoyometer" class="nav-link active" data-scroll-target="#yoyometer">Yoyometer</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a>
  <ul class="collapse">
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection">Data Collection</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#increased-attendance-after-relegation" id="toc-increased-attendance-after-relegation" class="nav-link" data-scroll-target="#increased-attendance-after-relegation">Increased attendance after relegation?</a></li>
  <li><a href="#and-in-general" id="toc-and-in-general" class="nav-link" data-scroll-target="#and-in-general">And in general?</a></li>
  </ul></li>
  <li><a href="#case-by-case-anomaly-handling" id="toc-case-by-case-anomaly-handling" class="nav-link" data-scroll-target="#case-by-case-anomaly-handling">Case-by-Case Anomaly Handling</a></li>
  <li><a href="#the-toxicity-factor-when-loyalty-snaps-and-when-it-doesnt" id="toc-the-toxicity-factor-when-loyalty-snaps-and-when-it-doesnt" class="nav-link" data-scroll-target="#the-toxicity-factor-when-loyalty-snaps-and-when-it-doesnt">The Toxicity Factor: When Loyalty Snaps (and When It Doesn’t)</a>
  <ul class="collapse">
  <li><a href="#a-results-business" id="toc-a-results-business" class="nav-link" data-scroll-target="#a-results-business">A Results Business</a></li>
  <li><a href="#would-champagne-football-help" id="toc-would-champagne-football-help" class="nav-link" data-scroll-target="#would-champagne-football-help">Would champagne football help?</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a>
  <ul class="collapse">
  <li><a href="#sources-1" id="toc-sources-1" class="nav-link" data-scroll-target="#sources-1">Sources:</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/diggydigsdata/blob/main/posts/post-relegation-attendance/index.ipynb" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<p>I’m a Burnley fan. With our recent promotion to the Premier League we are firmly consolidated as a yoyo club par excellence - we rank joint-4th with Sunderland on the Yoyo-meter (below). So what better time to assess some of the impacts of relegation from the Premier League? Because it’s never too early to plan ahead.</p>
<p>In this article, I’ll be exploring if, how and for how long Premier League relegation disrupts attendances. We’ll also examine some mitigating factors. Does attractive football help maintain attendances? Is mid-table mediocrity worse for attendances than being in a relegation dogfight?</p>
<p>The dataset I have designed for this project combines a few different online resources and also engineers some variables. You can read about it and download it <a href="../too-messy-to-melt/">here</a>.</p>
<section id="yoyometer" class="level3">
<h3 class="anchored" data-anchor-id="yoyometer">Yoyometer</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 19%">
<col style="width: 30%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Club</th>
<th>PL Relegations</th>
<th>Championship Promotions</th>
<th>Current League</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Norwich City</td>
<td>6</td>
<td>5</td>
<td>Championship</td>
</tr>
<tr class="even">
<td>West Bromwich Albion</td>
<td>5</td>
<td>5</td>
<td>Championship</td>
</tr>
<tr class="odd">
<td>Leicester City</td>
<td>5</td>
<td>5</td>
<td>Championship</td>
</tr>
<tr class="even">
<td>Burnley</td>
<td>4</td>
<td>5</td>
<td>Premier League</td>
</tr>
<tr class="odd">
<td>Sunderland</td>
<td>4</td>
<td>5</td>
<td>Premier League</td>
</tr>
<tr class="even">
<td>Crystal Palace</td>
<td>4</td>
<td>4</td>
<td>Premier League</td>
</tr>
<tr class="odd">
<td>Middlesbrough</td>
<td>4</td>
<td>4</td>
<td>Championship</td>
</tr>
<tr class="even">
<td>Watford</td>
<td>4</td>
<td>4</td>
<td>Championship</td>
</tr>
<tr class="odd">
<td>Sheffield United</td>
<td>4</td>
<td>3</td>
<td>Championship</td>
</tr>
<tr class="even">
<td>Southampton</td>
<td>3</td>
<td>2</td>
<td>Championship</td>
</tr>
</tbody>
</table>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<section id="data-collection" class="level3">
<h3 class="anchored" data-anchor-id="data-collection">Data Collection</h3>
<p>For this project, I gathered attendance, league position, and performance data for every club relegated from the Premier League, spanning a four-year period for each event:</p>
<ol type="1">
<li>Year -1: The season before the Premier League relegation season.</li>
<li>Year 0: The Premier League season that resulted in relegation.</li>
<li>Year +1: The first season after relegation (in the Championship).</li>
<li>Year +2: The second season after relegation.</li>
</ol>
<p>A temporary fifth year of data (Year +3) was programmatically generated to extract the league tier, which is used to determine the final outcome of the Year +2 season. After achieving that, the temporary Year +3 data was dropped.</p>
<section id="sources" class="level4">
<h4 class="anchored" data-anchor-id="sources">Sources</h4>
<ol type="1">
<li><p>For <strong>Attendance data</strong>, I referenced <a href="https://www.european-football-statistics.co.uk/index1.htm">European-Football-Statistics.co.uk</a>.</p></li>
<li><p>For <strong>Position data</strong> and <strong>Performance data</strong> I incorporated data from the Fjelstul English Football Database, which is a comprehensive catalogue of English Football from 1888-2024. I used only a small section from the standings dataset, but he also has datasets covering seasons, teams, matches and appearances. Worth a look if you have a project in mind. The database is copyrighted (“© 2024 Joshua C. Fjelstul, Ph.D.”) but accessible via the CC-BY-SA 4.0 license (https://creativecommons.org/licenses/by-sa/4.0/legalcode).</p></li>
</ol>
<p>I will also be making my own dataset available under the same CC-BY-SA 4.0 license.</p>
<p>Fjelstul, Joshua C. “The Fjelstul English Football Database v1.1.0.” May 26, 2024. <a href="https://www.github.com/jfjelstul/englishfootball">https://www.github.com/jfjelstul/englishfootball</a>.</p>
</section>
</section>
<section id="dataset" class="level3">
<h3 class="anchored" data-anchor-id="dataset">Dataset</h3>
<p>In addition to merging attendance data with position data and performance data, some key features of the dataset had to be engineered. I needed <code>Year_vs_Relegation</code> and <code>Year_End_Outcome</code> columns in order to group by season outcomes and to track attendance over time.</p>
<p>For my <em>single source of truth</em> dataset, I am using the raw values for performance (Points, Goals, etc.) and calculating per-game metrics as needed for analysis. Below is a snapshot of the final, tidy dataset.</p>
<section id="limitations" class="level4">
<h4 class="anchored" data-anchor-id="limitations">Limitations</h4>
<p>As tidy as it is, there are still some pretty big limitations to this dataset:</p>
<p><strong>Season-Level Granularity</strong>:<br>
- The dataset aggregates data at the season level, meaning any within-season events—such as managerial changes, mid-season form swings, or cup runs—are not captured.</p>
<p><strong>Loss of Match-Level Variability</strong>:<br>
- Attendance figures are averaged per season, so high- or low-attendance matches (e.g., local derbies) are smoothed out.</p>
<p><strong>External Influences Aren’t Captured</strong> (with the exception of COVID) - Factors such as weather, ticket pricing, fan protests, or extraordinary events (e.g., stadium closures) are not included. These could all contribute to unexplained variance in attendance. However, I do think that over a season, these sorts of things tend to balance themselves out. Except for COVID and stadium reconstructions, which both need special handling.</p>
<p><strong>Handling COVID-19</strong><br>
- A quick note on the elephant in the stadium: the 2019-20 and 2020-21 seasons. Since many games were played with zero or partial attendance, including them as “0” would catastrophically skew the averages. To prevent this, the data cleaning pipeline explicitly searches for any attendance data marked “COVID” and converts it to a null value (<code>pd.NA</code>). All subsequent averaging functions automatically ignore these null values, so the analysis is not contaminated by seasons played behind closed doors.</p>
<p><strong>Handling Stadium Anomalies</strong> The data contains three major structural anomalies where attendance was dictated by stadium construction, not fan sentiment or on-pitch performance:</p>
<ol type="1">
<li><p>Middlesbrough (1993-94): Attendance artificially plummeted due to a stadium rebuild.</p></li>
<li><p>Sunderland (1997-98): Attendance saw a massive, artificial spike from moving to the new Stadium of Light.</p></li>
<li><p>Leicester City (2002-03): A similar spike occurred when the club moved to the Walkers Stadium (now called the King Power Stadium).</p></li>
</ol>
<p>To prevent these outliers from skewing my interpretations, these specific team-seasons were identified. Unless I specifically mention their inclusion, you can safely assume they were filtered out of the analysis.</p>
</section>
<section id="downloadable" class="level4">
<h4 class="anchored" data-anchor-id="downloadable">Downloadable</h4>
<p>If you still want the dataset for analysis after all that, or you’re wondering why I keep calling things tidy, then check out <a href="../too-messy-to-melt/">Too Messy to Melt</a> for a technical guide to how this dataset was constructed. Or you can inspect the data dictionary and grab the downloadable dataset straight from my GitHub.</p>
</section>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<section id="increased-attendance-after-relegation" class="level3">
<h3 class="anchored" data-anchor-id="increased-attendance-after-relegation">Increased attendance after relegation?</h3>
<p>Let’s start on a positive note. On 10 occasions, teams managed to increase their average attendance in the first season (Y+1) immediately following relegation.</p>
<div id="cell-11" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;ExecuteTime&quot;,&quot;value&quot;:{&quot;end_time&quot;:&quot;2025-11-10T08:57:25.049565Z&quot;,&quot;start_time&quot;:&quot;2025-11-10T08:57:25.038752Z&quot;}}" data-cap="Table 1: Teams with Increased Attendance in Year +1" data-execution_count="70">
<div class="cell-output cell-output-stdout">
<pre><code>
--- TABLE 1: Increased Attendance (Year +1) ---
| Team              |   Attendance (Y0) |   Attendance (Y+1) |   Change (%) |
|:------------------|------------------:|-------------------:|-------------:|
| Sunderland        |             20865 |              33492 |        60.52 |
| Leicester City    |             19835 |              29231 |        47.37 |
| Nottingham Forest |             21910 |              23051 |         5.21 |
| Ipswich Town      |             24426 |              25455 |         4.21 |
| Burnley           |             19399 |              19953 |         2.86 |
| Newcastle United  |             49754 |              51106 |         2.72 |
| Norwich City      |             24350 |              24952 |         2.47 |
| Crystal Palace    |             14992 |              15248 |         1.71 |
| Luton Town        |             11244 |              11420 |         1.57 |
| Middlesbrough     |             29848 |              29994 |         0.49 |</code></pre>
</div>
</div>
<p>And I have to give a shoutout to Burnley and, indeed, to Vincent Kompany because he certainly galvanised the supporters that season.</p>
<p>A couple teams really jump out. Both Sunderland and Leicester City moved into new stadia the year after their relegation, and this gave them a considerable bump. They must have been absolutely packing out their stadia the season prior and had supporters banging down the doors to get in. Sunderland even managed to add over 5,000 supporters to their tally the season after relegation, despite the fact that they were still stuck in the Championship. Leicester also increased attendances in 2003-04, by 1,600 to 30,983. But they spent that season in the Premier League, so it’s less startling to see an increase.</p>
<p>Newcastle also catch the eye, but not just because their 51,106 fans in 2016-17 is an extraordinary number - everyone knows Newcastle is a football-mad city. What’s truly insightful is comparing their two most recent relegations.</p>
<ul>
<li><p>After relegation in 2009, the club saw a significant 11% <em>drop</em> in average attendance.</p></li>
<li><p>After relegation in 2016-17, The club saw a 2.7% <em>increase</em> in attendance.</p></li>
</ul>
<p>That’s 13.7-point swing. The club was massive in both scenarios, so “big club” is a constant. The most obvious variable is “vibes.”</p>
<p>At the end of 2008-09 Newcastle’s all-time record goalscorer and local lad Alan Shearer had stepped up to try and save Newcastle. He only had 8 games to do it in. No matter the outcome, he was supposed to stay on as manager into the next season. But they got relegated and he didn’t get offered a contract for the next season. There’s no doubt that this was a low point between Newcastle fans and their owner Mike Ashley. And this was borne out in the 2009-10 attendances.</p>
<p>2016-17 was the polar opposite. Similar to how Burnley fell under the spell of Vincent Kompany in 2022/23, Newcastle fans had a great relationship with Rafael Benitez, even if Mike Ashley was still as loathed as ever. Benitez was hired towards the end of their 2015/16 relegation season and it was considered quite a coup to attract this Champions League-winning manager to a Championship-bound club. So the fans showed their appreciation during his first full season in charge with record-breaking attendances.</p>
<!--Typically, we start to see the cracks in season 2 outside the top flight. Filtering out teams like Leicester who were promoted at the first attempt and had Premier League fixtures to pull in the fans, only 6 teams see attendance figures in the black by season 2.-->
</section>
<section id="and-in-general" class="level3">
<h3 class="anchored" data-anchor-id="and-in-general">And in general?</h3>
<p>Those positive stories are, unfortunately, the exceptions. On average, attendance falls significantly. But to find the real signal, we must first identify and handle the noise.</p>
<p>A box plot of all post-relegation data (Y+1 and Y+2) shows the wild variance in outcomes.</p>
<div id="cell-14" class="cell" data-execution_count="76">
<div class="cell-output cell-output-stdout">
<pre><code>
--- PLOT: Box Plot for Distribution (All Data Included) ---</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-2.png" class="img-fluid figure-img"></p>
<figcaption>Distribution of attendance change (Y+1 &amp; Y+2) by outcome, including all outliers and sample sizes.</figcaption>
</figure>
</div>
</div>
</div>
<p>The plot above clearly shows several extreme statistical outliers (the dots) that are skewing the data. To understand what they are, we can use the <code>1.5 * IQR</code> rule (the same logic the box plot uses) to print a list of them.</p>
<div id="cell-16" class="cell" data-execution_count="72">
<div class="cell-output cell-output-stdout">
<pre><code>
--- Outlier Hunt (Using 1.5 * IQR Rule) ---

--- Outliers for 'Promoted' (Outside -22.31 to 17.73) ---
| Relegation_Event_ID      |   Year_vs_Relegation |   Pct_Change_vs_Y0_Display |
|:-------------------------|---------------------:|---------------------------:|
| Leicester City 2001-02   |                    2 |                      56.20 |
| Leicester City 2001-02   |                    1 |                      47.37 |
| Bolton Wanderers 1995-96 |                    2 |                      29.38 |
| Sunderland 2005-06       |                    2 |                      27.84 |
| Fulham 2018-19           |                    1 |                     -25.30 |
| Hull City 2014-15        |                    1 |                     -26.99 |
| Birmingham City 2007-08  |                    1 |                     -27.12 |

--- Outliers for 'Survived' (Outside -53.88 to 17.15) ---
| Relegation_Event_ID   |   Year_vs_Relegation |   Pct_Change_vs_Y0_Display |
|:----------------------|---------------------:|---------------------------:|
| Sunderland 1996-97    |                    2 |                      85.69 |
| Sunderland 1996-97    |                    1 |                      60.52 |
| Wimbledon 1999-2000   |                    1 |                     -53.95 |
| Wimbledon 1999-2000   |                    2 |                     -59.43 |</code></pre>
</div>
</div>
</section>
</section>
<section id="case-by-case-anomaly-handling" class="level2">
<h2 class="anchored" data-anchor-id="case-by-case-anomaly-handling">Case-by-Case Anomaly Handling</h2>
<p>This list gives us a clear action plan. To understand the true relationship between performance and attendance, we must filter out cases where attendance was driven by external structural factors, not fan behavior.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 21%">
<col style="width: 11%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Relegation Event</th>
<th>Year</th>
<th>Change</th>
<th>Outlier Type</th>
<th>Decision</th>
<th>Reason</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sunderland 1996-97</td>
<td>Y+1, Y+2</td>
<td>+61%, +86%</td>
<td>Stadium Anomaly</td>
<td>Remove</td>
<td>Moved to the new, much larger Stadium of Light.</td>
</tr>
<tr class="even">
<td>Leicester City 2001-02</td>
<td>Y+1, Y+2</td>
<td>+47%, +56%</td>
<td>Stadium Anomaly</td>
<td>Remove</td>
<td>Moved to the new Walkers (King Power) Stadium.</td>
</tr>
<tr class="odd">
<td>Bolton Wanderers 1995-96</td>
<td>Y+2</td>
<td>+29%</td>
<td>Stadium Anomaly</td>
<td>Remove</td>
<td>Y+2 (1997-98 season) was their first in the new Reebok Stadium.</td>
</tr>
<tr class="even">
<td>Middlesbrough 1992-93</td>
<td>Y+1</td>
<td>-38%</td>
<td>Stadium Anomaly</td>
<td>Remove</td>
<td>Attendance nosedived during a stadium rebuild.</td>
</tr>
<tr class="odd">
<td>Wimbledon 1999-2000</td>
<td>Y+1, Y+2</td>
<td>-54%, -59%</td>
<td>Toxicity</td>
<td>Keep</td>
<td>To be continued…</td>
</tr>
<tr class="even">
<td>Hull City 2014-15</td>
<td>Y+1</td>
<td>-27%</td>
<td>Toxicity</td>
<td>Keep</td>
<td>To be continued…</td>
</tr>
<tr class="odd">
<td>Birmingham City 2007-08</td>
<td>Y+1</td>
<td>-27%</td>
<td>Toxicity</td>
<td>Keep</td>
<td>To be continued…</td>
</tr>
</tbody>
</table>
<p>Now, with the data properly filtered, let’s look at the real story.</p>
<p>And we may as well start with that Toxicity factor I mentioned above.</p>
</section>
<section id="the-toxicity-factor-when-loyalty-snaps-and-when-it-doesnt" class="level2">
<h2 class="anchored" data-anchor-id="the-toxicity-factor-when-loyalty-snaps-and-when-it-doesnt">The Toxicity Factor: When Loyalty Snaps (and When It Doesn’t)</h2>
<p>On-pitch performance isn’t the only driver. The data shows that a toxic or broken relationship between a club’s owners and its fans can act as a powerful accelerant for an attendance collapse.</p>
<p>These aren’t just “bad vibes”; they are measurable, real-world events:</p>
<p>Hull City (2014-15): The -27% drop in Y+1 wasn’t just about relegation. It directly coincided with a fan mutiny over the owners’ deeply unpopular attempt to rebrand the club as “Hull Tigers.”</p>
<p>Birmingham City (2007-08): A similar story. Their -27% nosedive in Y+1 was fueled by widespread fan protests calling for the board to resign.</p>
<p>Newcastle (2009-10 vs.&nbsp;2016-17): This is the perfect A/B test. In both 2009 and 2016, the club had the same toxic ownership under Mike Ashley.</p>
<p>In 2009-10, the vibe was poisonous. The result? A significant 11% drop in attendance.</p>
<p>In 2016-17, a different “vibe” won. Hiring (and keeping) Rafa Benitez was such an unexpected coup that his popularity papered over the cracks, galvanizing the fanbase and leading to a 2.7% increase.</p>
<p>Wimbledon (1999-2000): This is the ultimate case study. They were already a “homeless” club, playing at Crystal Palace’s Selhurst Park during their Y0 relegation season. Their baseline attendance was already depressed. When they lost their Premier League status, attendance collapsed by -59%. The showpiece occasion of a Premier League game seems to have been the last thread holding that displaced fanbase together. When it snapped, so did the club.</p>
<section id="a-results-business" class="level3">
<h3 class="anchored" data-anchor-id="a-results-business">A Results Business</h3>
<p>Next up, we’ll look at our <code>Year_End_Outcome</code> variable. Let’s plot the attendance change over time, grouping teams by whether they were Promoted, Survived, or Relegated in their first post-relegation season.</p>
<div id="cell-20" class="cell" data-execution_count="73">
<div class="cell-output cell-output-stdout">
<pre><code>
--- PLOT 1: Attendance Change by Y+1 Outcome (Final Filter) ---

--- New Averages for Analysis ---
| Outcome_Group   |   Year_vs_Relegation |   Pct_Change_vs_Y0_Display |
|:----------------|---------------------:|---------------------------:|
| Promoted        |                    1 |                       -8.5 |
| Promoted        |                    2 |                        2.0 |
| Relegated       |                    1 |                      -20.7 |
| Relegated       |                    2 |                      -17.5 |
| Survived        |                    1 |                      -17.2 |
| Survived        |                    2 |                      -21.6 |</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-10-output-2.png" class="img-fluid figure-img"></p>
<figcaption>Average attendance change (anomalies removed) relative to the relegation season (Y0), grouped by the team’s outcome in their first post-relegation season (Y+1).</figcaption>
</figure>
</div>
</div>
</div>
<p>Irrespective of season outcome, relegated teams <em>on average</em> lose fans. And there seems to be a clear correlation between team performance and attendance. Moreover, it does seem that performance affects attendances.</p>
<p><strong>Promoted (Green Line)</strong>: Teams that bounce straight back (like Burnley) see their Y+1 attendance drop minimized to just -8.6%. By Y+2, they are back in the Premier League, and attendance recovers to surpass its pre-relegation level by 2%.</p>
<p><strong>Survived (Blue Line)</strong>: Teams that “survive” and stay in the Championship see a much larger initial drop of -17.2%. Worse, by Y+2, that optimism fades and attendance dwindles further to -21.6%.</p>
<p><strong>Relegated (Orange Line)</strong>: Teams that enter freefall and plummet into League 1 see a catastrophic -28% drop in Y+1, which slightly recovers to -24% in Y+2.</p>
</section>
<section id="would-champagne-football-help" class="level3">
<h3 class="anchored" data-anchor-id="would-champagne-football-help">Would champagne football help?</h3>
<p>If you’re stuck in the Championship, can you at least keep the fans entertained with attacking football?</p>
<p>To test this, I’ve plotted <code>Goals_For_Per_Game</code> against the percentage change in attendance for all post-relegation seasons (Y+1 and Y+2), again grouped by the team’s outcome and with the stadium anomalies removed.</p>
<div id="cell-23" class="cell" data-execution_count="74">
<div class="cell-output cell-output-stdout">
<pre><code>
--- PLOT 2: Goals vs. Attendance % Change (Final Filter) ---</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-11-output-2.png" class="img-fluid figure-img"></p>
<figcaption>Scatter plots (all structural anomalies removed) showing the relationship between attacking football and the percentage change in attendance.</figcaption>
</figure>
</div>
</div>
</div>
<p>The answer seems to be: yes, but only if you have nothing else to play for.</p>
<p>For Survived teams, there is a fairly clear positive relationship. If a team is destined for another year of mid-table Championship football, entertainment value (scoring goals) seems to help keep traffic coming through the turnstiles.</p>
<!-- Luton really buck the trend for League 1-destined sides. And because there are so few teams who are relegated from the Premier League to League 1 in consecutive seasons, their outlier status has a huge impact on the data, dropping the averages by almost 8%. But can Luton really be considered anomalous when the data population is so small? In my view, yes. First of all, Luton had an emotional relegation season. Their captain Tom Lockyer suffered a cardiac arrest mid-game. Fortunately, he survived and has been on a road to recovery ever since with the view to playing again. Moreover, Luton battled very bravely against relegation despite these traumatising events and despite being financial minnows. Luton were a uniquely united club during their relegation season. However, that is not the only explanation. The other is that Luton are another stadium-constrained side. Kenilworth Road is famously tiny, and was a peculiar relic among Premier League stadiums. Luton have received approval for a stadium rebuild that will double its capacity. Based on their increased attendances post-relegation, Luton are another case of a club where demand has exceeded supply for some time.-->
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<ul>
<li>Teams can typically expect to lose 16-22% of their attendance after relegation if they don’t bounce straight back, and that drop accelerates in the second year.</li>
<li>If you are on track for promotion, losses are minimized to ~8% and attendance fully recovers upon returning to the Premier League. “Vibes” (like a popular manager), “toxicity” (like a detested owner) and “style” (attacking football) seem to be real factors. Style is most visible for teams stuck in mid-table, where the on-pitch result isn’t exciting enough on its own. But vibes and toxicity can keep a club afloat or cause it to sink.</li>
<li>And if you are on track for League 1, these losses are considerably higher</li>
<li>Relegation doesn’t automatically mean fan abandonment. Context matters: management, entertainment value, stadium capacity, and hope for promotion all play a role.</li>
</ul>
<section id="sources-1" class="level3">
<h3 class="anchored" data-anchor-id="sources-1">Sources:</h3>
<p>Fjelstul, Joshua C. “The Fjelstul English Football Database v1.1.0.” May 26, 2024. <a href="https://www.github.com/jfjelstul/englishfootball">https://www.github.com/jfjelstul/englishfootball</a></p>
<p><a href="https://www.european-football-statistics.co.uk/index1.htm">European-Football-Statistics.co.uk</a></p>
<p>Thumbnail image courtesy of <a href="https://commons.wikimedia.org/wiki/File:Brno_-_Abandoned_soccer_stadium.jpg">Jaroslav A. Polák from Brno, Czech Republic</a>, CC0, via Wikimedia Commons</p>


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div class="quarto-appendix-contents"><div><a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a></div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    window.setColorSchemeToggle(window.hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/diggydigsdata\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>This page is built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/diggydigsdata/blob/main/posts/post-relegation-attendance/index.ipynb" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../LICENSE">
<p>License</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>